[toolchain]
channel = "nightly"
components = [
  "rust-src"
]

[build]
target = "x86_64-kernel.json"

[unstable]
build-std = [
  "alloc",
  "core",
  "compiler_builtins"
]
build-std-features = [
  "compiler-builtins-mem"
]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
